<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="4" passed="2" failed="1" skipped="1">
  <reporter-output>
  </reporter-output>
  <suite started-at="2025-02-06T17:02:50 IST" name="Suite" finished-at="2025-02-06T17:03:06 IST" duration-ms="16197">
    <groups>
    </groups>
    <test started-at="2025-02-06T17:02:50 IST" name="Test" finished-at="2025-02-06T17:03:06 IST" duration-ms="16197">
      <class name="assertion.HardAssertion">
        <test-method is-config="true" signature="initialization(java.lang.String,java.lang.String)[pri:0, instance:assertion.HardAssertion@6340e5f0]" started-at="2025-02-06T17:02:50 IST" name="initialization" finished-at="2025-02-06T17:02:52 IST" duration-ms="2163" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[Chrome]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[https://katalon-demo-cura.herokuapp.com/]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initialization -->
        <test-method signature="checkWindowTitle()[pri:0, instance:assertion.HardAssertion@6340e5f0]" started-at="2025-02-06T17:02:52 IST" name="checkWindowTitle" finished-at="2025-02-06T17:02:55 IST" duration-ms="3090" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- checkWindowTitle -->
        <test-method is-config="true" signature="initialization(java.lang.String,java.lang.String)[pri:0, instance:assertion.HardAssertion@6340e5f0]" started-at="2025-02-06T17:02:55 IST" name="initialization" finished-at="2025-02-06T17:02:57 IST" duration-ms="1779" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[Chrome]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[https://katalon-demo-cura.herokuapp.com/]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initialization -->
        <test-method signature="checkUrl()[pri:2, instance:assertion.HardAssertion@6340e5f0]" started-at="2025-02-06T17:02:57 IST" name="checkUrl" finished-at="2025-02-06T17:03:01 IST" duration-ms="4019" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [https://katalon-demo-cura.herokuapp.com/] but found [http://www.facebook.com]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [https://katalon-demo-cura.herokuapp.com/] but found [http://www.facebook.com]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at assertion.HardAssertion.checkUrl(HardAssertion.java:64)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- checkUrl -->
        <test-method is-config="true" signature="initialization(java.lang.String,java.lang.String)[pri:0, instance:assertion.HardAssertion@6340e5f0]" started-at="2025-02-06T17:03:01 IST" name="initialization" finished-at="2025-02-06T17:03:02 IST" duration-ms="1584" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[Chrome]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[https://katalon-demo-cura.herokuapp.com/]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initialization -->
        <test-method signature="checkHeadingDisplayed()[pri:3, instance:assertion.HardAssertion@6340e5f0]" started-at="2025-02-06T17:03:02 IST" name="checkHeadingDisplayed" finished-at="2025-02-06T17:03:06 IST" duration-ms="3492" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- checkHeadingDisplayed -->
        <test-method signature="checkMakeAppointemnt()[pri:4, instance:assertion.HardAssertion@6340e5f0]" started-at="2025-02-06T17:03:06 IST" name="checkMakeAppointemnt" finished-at="2025-02-06T17:03:06 IST" depends-on-methods="assertion.HardAssertion.checkUrl" duration-ms="1" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method assertion.HardAssertion.checkMakeAppointemnt() on instance assertion.HardAssertion@6340e5f0 depends on not successfully finished methods 
[assertion.HardAssertion.checkUrl() on instance assertion.HardAssertion@6340e5f0]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method assertion.HardAssertion.checkMakeAppointemnt() on instance assertion.HardAssertion@6340e5f0 depends on not successfully finished methods 
[assertion.HardAssertion.checkUrl() on instance assertion.HardAssertion@6340e5f0]
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:159)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- checkMakeAppointemnt -->
      </class> <!-- assertion.HardAssertion -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
